### ISSUE TITLE
brzdm -v

### ISSUE THREAD

**Issue by smxi** [dev-breeze-com/brzdm#2]
I'm trying to complete brzdm support for inxi, what is the output of: brzdm -v
verbatim, that is, the literal output.

And also, to confirm, does brzdm use /run, and what is the name of its runfile, which is the default inxi uses to detect a running dm.

**Comment by dev-breeze-com** [comment]
The answer is in the files src/app.cc and brzdm.conf respectively.

**Comment by smxi** [comment]
It took you longer to type that than it would have taken you to just show the output. Whatever... I'm not going to read through a few hundred lines of code to find something you could have just pasted in here now, that's frankly disrespectful, so I'm going to skip thinking about this any further.  Close the issue if this is how you think answering a simple question that takes you 1 second to provide the answer for works.

**Comment by dev-breeze-com** [comment]
If you really are who you say you are, then you must have a modicum of knowledge about software.
If you were really trying to customize your own system; you should not have asked the question in the first place.
A simple look at the code and how to configure the system would have given you all the information you wanted.

**Comment by smxi** [comment]
I asked you a simple question which would have taken you all of 1 second to provide the data for. I don't care about configuring the code or brzdm outside of wanting to  make sure inxi handled the version data correctly which requires seeing the physical output which can never be assumed. The fact that you refuse to do this suggests to me that either you aren't using brzdm and thus can't do it, or some other weird thing. 

This was a courtesy to your project to try to include full  support for your dm, but I'm going to assume it's a dead project and not worth thinking about anymore. But inxi still supports it, it supports many dead wm and dms. Usually when I ask obscure projects used by virtually nobody for such information, they are pleased that someone out there is actually aware of their stuff and cares enough to take the time to ask.

For the record, I went on the assumption that the actual version number is the third 'word' in the output, space separated since that's what SLiM and slimski have.

Next time just read the question and answer it, don't make people jump through stupid hoops just because you can't understand or process an elementary question in simple english.

Sorry I wasted my time on this.
